/**
 * Generates COVERAGE.md by walking the commander tree that src/program.ts
 * builds. Run via `npm run gen-coverage`.
 *
 * Unlike the api-client's equivalent — which has to parse src/client.ts with
 * the TypeScript compiler API, because methods are just code — commander hands
 * us the real structure at runtime: every command, its arguments, its options
 * and their descriptions. So this walks the exact same object the CLI
 * registers, and the doc cannot drift from it by construction.
 *
 * `npm run check-coverage` regenerates and fails on a dirty tree; CI runs that
 * as the drift guard. If you add a command or flag and CI goes red here, run
 * `npm run gen-coverage` and commit the result.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { Command, Option } from "commander";

import { buildProgram } from "../src/program.js";

const here = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(here, "..", "COVERAGE.md");

interface Leaf {
  /** Full invocation, e.g. `quire task timelog add <id>`. */
  usage: string;
  description: string;
  options: Option[];
}

/** The top-level group a command belongs to — `task` for `quire task update`. */
function groupOf(path: string[]): string {
  return path[0] ?? "";
}

/**
 * Collect every runnable command. A command with subcommands is a namespace
 * rather than something you can invoke, so only leaves are listed; commander's
 * auto-generated `help` subcommands are skipped.
 */
function collectLeaves(cmd: Command, path: string[] = []): Leaf[] {
  const out: Leaf[] = [];
  for (const sub of cmd.commands) {
    if (sub.name() === "help") continue;
    const subPath = [...path, sub.name()];
    if (sub.commands.filter((c) => c.name() !== "help").length === 0) {
      const args = sub.registeredArguments.map((a) => (a.required ? `<${a.name()}>` : `[${a.name()}]`));
      out.push({
        usage: ["quire", ...subPath, ...args].join(" "),
        description: sub.description(),
        options: [...sub.options],
      });
    } else {
      out.push(...collectLeaves(sub, subPath));
    }
  }
  return out;
}

/** Escape the pipes and newlines that would break a Markdown table cell. */
function cell(text: string): string {
  return text.replace(/\s*\n\s*/g, " ").replace(/\|/g, "\\|").trim();
}

function flagSpec(o: Option): string {
  return o.flags.replace(/\|/g, "\\|");
}

function main(): void {
  const program = buildProgram();
  const leaves = collectLeaves(program);

  // Group in registration order — that is the order src/program.ts wires them
  // up, which is also the order `quire --help` lists them.
  const groups = new Map<string, Leaf[]>();
  for (const leaf of leaves) {
    const g = groupOf(leaf.usage.split(" ").slice(1));
    const list = groups.get(g);
    if (list) list.push(leaf);
    else groups.set(g, [leaf]);
  }

  const totalFlags = leaves.reduce((n, l) => n + l.options.length, 0);

  const lines: string[] = [
    "<!-- Generated by scripts/gen-coverage.ts from src/program.ts. Run `npm run gen-coverage` to refresh. -->",
    "",
    "# Command Coverage",
    "",
    "Every runnable `quire` command, with its flags. Generated from the commander tree in",
    "[`src/program.ts`](src/program.ts), so it cannot drift from what the CLI actually registers.",
    "",
    `Generated from ${String(leaves.length)} commands across ${String(groups.size)} groups, with ${String(totalFlags)} flags.`,
    "",
    "Global flags apply to every command and are listed once at the end.",
    "",
  ];

  // Contents — handy at this size, and a quick way to see the groups.
  lines.push("## Contents", "");
  for (const g of groups.keys()) {
    lines.push(`- [\`quire ${g}\`](#quire-${g})`);
  }
  lines.push("", "---", "");

  for (const [g, items] of groups) {
    lines.push(`## quire ${g}`, "");
    for (const leaf of items) {
      lines.push(`### \`${leaf.usage}\``, "");
      if (leaf.description) lines.push(cell(leaf.description), "");
      if (leaf.options.length > 0) {
        lines.push("| Flag | Description |", "|---|---|");
        for (const o of leaf.options) {
          lines.push(`| \`${flagSpec(o)}\` | ${cell(o.description)} |`);
        }
        lines.push("");
      }
    }
  }

  lines.push("---", "", "## Global flags", "");
  lines.push("| Flag | Description |", "|---|---|");
  for (const o of program.options) {
    lines.push(`| \`${flagSpec(o)}\` | ${cell(o.description)} |`);
  }
  lines.push("");

  writeFileSync(outPath, lines.join("\n"));
  process.stderr.write(
    `Wrote COVERAGE.md — ${String(leaves.length)} commands, ${String(totalFlags)} flags.\n`,
  );
}

main();
